version: "3.9"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Kolkata
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Djenkins.winstone.http2=false
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc/jenkins.yaml
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - APIFY_TOKEN_DEV=${APIFY_TOKEN_DEV}
      - APIFY_TOKEN_PROD=${APIFY_TOKEN_PROD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GID:-998}"
    restart: unless-stopped
volumes:
  jenkins_home:
    name: jenkins_home
