version: "3.9"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    user: "0:0"
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Kolkata
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins.yaml
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - APIFY_TOKEN_DEV=${APIFY_TOKEN_DEV}
      - APIFY_TOKEN_PROD=${APIFY_TOKEN_PROD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc:/var/jenkins_home/casc:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  jenkins_home:
    name: jenkins_home
