jenkins:
  systemMessage: "Apify Actors CI/CD — Managed by JCasC"
  numExecutors: 2
  mode: NORMAL
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD}"

unclassified:
  location:
    url: "${JENKINS_URL}"
  gitHubConfiguration:
    endpoints:
      - name: "github"
        apiUri: "https://api.github.com"

  globalLibraries:
    libraries:
      - name: "apify-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/QuickLifeSolutions/jenkins-apify-lib.git"
                credentialsId: "github-token"
        defaultVersion: "main"
        allowVersionOverride: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-token"
              scope: GLOBAL
              description: "GitHub PAT: repo, admin:repo_hook"
              username: "x-access-token"
              password: "${GITHUB_TOKEN}"
          - string:
              id: "apify-token-dev"
              scope: GLOBAL
              description: "APIFY_TOKEN (DEV)"
              secret: "${APIFY_TOKEN_DEV}"
          - string:
              id: "apify-token-prod"
              scope: GLOBAL
              description: "APIFY_TOKEN (PROD)"
              secret: "${APIFY_TOKEN_PROD}"

tool:
  git:
    installations:
      - name: "git"
        home: "/usr/bin/git"

jobs:
  - script: |
      organizationFolder('QuickLifeSolutions') {
        displayName('QuickLifeSolutions')
        organizations {
          github {
            repoOwner('QuickLifeSolutions')
            credentialsId('github-token')
            traits {
              gitHubExcludeArchivedRepositories()
            }
            configure { navigator ->
              def traits = navigator / 'traits'
              traits.children().clear()
              def branchDiscovery = traits.appendNode('org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait')
              branchDiscovery.appendNode('strategyId', 3)
              traits.appendNode('org.jenkinsci.plugins.github_branch_source.TagDiscoveryTrait')
              def prDiscovery = traits.appendNode('org.jenkinsci.plugins.github_branch_source.PullRequestDiscoveryTrait')
              prDiscovery.appendNode('strategyId', 3)
              def wildcardFilter = traits.appendNode('jenkins.plugins.git.traits.WildcardSCMHeadFilterTrait')
              wildcardFilter.appendNode('includes', '*')
              wildcardFilter.appendNode('excludes', '')
              def topicsFilter = traits.appendNode('org.jenkinsci.plugins.github_branch_source.TopicsTrait')
              topicsFilter.appendNode('includes', 'apify-actor')
              topicsFilter.appendNode('excludes', '')
            }
          }
        }
        projectFactories {
          workflowMultiBranchProjectFactory {
            scriptPath('ci/Jenkinsfile')
          }
        }
        orphanedItemStrategy { discardOldItems { daysToKeep(30); numToKeep(60) } }
      }
