jenkins:
  systemMessage: "Apify Actors CI/CD — Managed by JCasC"
  numExecutors: 2
  mode: NORMAL
  nodes:
    - permanent:
        name: "aws-ec2"
        description: "AWS EC2 Ubuntu agent"
        remoteFS: "/opt/jenkins"
        labelString: "aws-ec2"
        numExecutors: 1
        mode: NORMAL
        retentionStrategy:
          always:
            checkInterval: 1
        launcher:
          ssh:
            host: "13.200.56.3"
            port: 22
            credentialsId: "aws-ec2-agent"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              nonVerifyingKeyVerificationStrategy: {}
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD}"

unclassified:
  location:
    url: "${JENKINS_URL}"
  gitHubConfiguration:
    endpoints:
      - name: "github"
        apiUri: "https://api.github.com"

  globalLibraries:
    libraries:
      - name: "apify-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/QuickLifeSolutions/jenkins-apify-lib.git"
                credentialsId: "github-token"
        defaultVersion: "main"
        allowVersionOverride: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-token"
              scope: GLOBAL
              description: "GitHub PAT: repo, admin:repo_hook"
              username: "x-access-token"
              password: "${GITHUB_TOKEN}"
          - string:
              id: "apify-token-dev"
              scope: GLOBAL
              description: "APIFY_TOKEN (DEV)"
              secret: "${APIFY_TOKEN_DEV}"
          - string:
              id: "apify-token-prod"
              scope: GLOBAL
              description: "APIFY_TOKEN (PROD)"
              secret: "${APIFY_TOKEN_PROD}"
          - basicSSHUserPrivateKey:
              id: "aws-ec2-agent"
              scope: GLOBAL
              description: "SSH key for AWS EC2 Jenkins agent"
              username: "ubuntu"
              privateKeySource:
                fileOnMaster: "/var/jenkins_home/secrets/aws_ec2_agent_key"

tool:
  git:
    installations:
      - name: "git"
        home: "/usr/bin/git"

jobs:
  - script: |
      organizationFolder('QuickLifeSolutions') {
        displayName('QuickLifeSolutions')
        organizations {
          github {
            repoOwner('QuickLifeSolutions')
            credentialsId('github-token')
            traits {
              gitHubExcludeArchivedRepositories()
              gitHubBranchDiscovery { strategyId(3) }
              gitHubTagDiscovery()
              gitHubPullRequestDiscovery { strategyId(3) }
              sourceWildcardFilter {
                includes('*')
                excludes('')
              }
            }
          }
        }
        projectFactories {
          workflowMultiBranchProjectFactory {
            scriptPath('ci/Jenkinsfile')
          }
        }
        orphanedItemStrategy { discardOldItems { daysToKeep(30); numToKeep(60) } }
      }
